### ISSUE TITLE
Erreur fatale lors du retour sur l'application (unmarshalling unknown type)

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#11]
Plusieurs rapports de crash avec l'exception suivante

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ayuget.redface/com.ayuget.redface.ui.TopicsActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@412b7e48: Unmarshalling unknown type code 464 at offset 856
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
at android.app.ActivityThread.access$600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@412b7e48: Unmarshalling unknown type code 464 at offset 856
at android.os.Parcel.readValue(Parcel.java:2032)
at android.os.Parcel.readListInternal(Parcel.java:2235)
at android.os.Parcel.readArrayList(Parcel.java:1655)
at android.os.Parcel.readValue(Parcel.java:1986)
at android.os.Parcel.readMapInternal(Parcel.java:2226)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1240)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:883)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1922)
at android.support.v4.app.Fragment.performCreate(Fragment.java:1776)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:915)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1136)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1118)
at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1922)
at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:266)
at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:122)
at com.ayuget.redface.ui.BaseActivity.onCreate(BaseActivity.java:42)
at com.ayuget.redface.ui.BaseDrawerActivity.onCreate(BaseDrawerActivity.java:100)
at com.ayuget.redface.ui.TopicsActivity.onCreate(TopicsActivity.java:93)
at android.app.Activity.performCreate(Activity.java:5104)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
... 11 more
```

**Comment by Ayuget** [comment]
J'ai apporté une modif sur le Parcelable de la classe Post, sur laquelle il y avait un writeLong / readInt.

Je doute que ça suffise à corriger, mais malheureusement la stack n'est pas très parlante sur l'origine réelle de l'erreur.
