### ISSUE TITLE
RxJava et cycle de vie d'une activity

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#27]
Parfois, une activity ou fragment reçoit un onNext de RxJava après que sa méthode onSaveInstanceState ait été appelée 

```
BaseDrawerActivity  E  Error on retrieving categories for user 'User{username='Guest'}'
                        E  java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                        E      at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1375)
                        E      at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1393)
                        E      at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:636)
                        E      at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:615)
                        E      at com.ayuget.redface.ui.TopicsActivity.onCategoryClicked(TopicsActivity.java:231)
                        E      at com.ayuget.redface.ui.TopicsActivity.loadDefaultCategory(TopicsActivity.java:217)
                        E      at com.ayuget.redface.ui.TopicsActivity.onCategoriesLoaded(TopicsActivity.java:199)
                        E      at com.ayuget.redface.ui.BaseDrawerActivity$1.onNext(BaseDrawerActivity.java:153)
                        E      at com.ayuget.redface.ui.BaseDrawerActivity$1.onNext(BaseDrawerActivity.java:149)
                        E      at rx.Observable$34.onNext(Observable.java:7212)
                        E      at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
                        E      at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
                        E      at rx.subjects.PublishSubject.onNext(PublishSubject.java:121)
                        E      at rx.Observable$34.onNext(Observable.java:7212)
                        E      at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
                        E      at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
                        E      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
                        E      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
                        E      at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
                        E      at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
                        E      at android.os.Handler.handleCallback(Handler.java:739)
                        E      at android.os.Handler.dispatchMessage(Handler.java:95)
                        E      at android.os.Looper.loop(Looper.java:135)
                        E      at android.app.ActivityThread.main(ActivityThread.java:5466)
                        E      at java.lang.reflect.Method.invoke(Native Method)
                        E      at java.lang.reflect.Method.invoke(Method.java:372)
                        E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
                        E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:733)
```

Il faudrait voir si le unsubscribe ne serait pas à faire dans le onPause, qui à réinitialiser le CompositeSubscription dans le onResume (attention aujourd'hui on subscribe pas mal dans le onCreate des fragments & activity,...)

**Comment by Ayuget** [comment]
Normalement adressé en version 2.0
