### ISSUE TITLE
Crash sur event reçu et traité after onSaveInstanceState

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#8]
Crash dans certains cas :
```
java.lang.RuntimeException: Could not dispatch event: class com.ayuget.redface.ui.event.TopicContextItemSelectedEvent to handler [EventHandler public void com.ayuget.redface.ui.TopicsActivity.onTopicContextItemSelected(com.ayuget.redface.ui.event.TopicContextItemSelectedEvent)]: Can not perform this action after onSaveInstanceState
       at com.squareup.otto.Bus.throwRuntimeException(Bus.java:456)
       at com.squareup.otto.Bus.dispatch(Bus.java:386)
       at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
       at com.squareup.otto.Bus.post(Bus.java:336)
       at com.ayuget.redface.ui.fragment.TopicListFragment.onContextItemSelected(TopicListFragment.java:480)
       at android.support.v4.app.Fragment.performContextItemSelected(Fragment.java:1909)
       at android.support.v4.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:2058)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:359)
       at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:152)
       at com.android.internal.policy.impl.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:4995)
       at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
       at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
       at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:172)
       at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1019)
       at android.widget.AdapterView.performItemClick(AdapterView.java:334)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1531)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3664)
       at android.widget.AbsListView$3.run(AbsListView.java:5585)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5940)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1375)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1393)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:636)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:615)
       at com.ayuget.redface.ui.TopicsActivity.loadTopic(TopicsActivity.java:289)
       at com.ayuget.redface.ui.TopicsActivity.onTopicContextItemSelected(TopicsActivity.java:346)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
       at com.squareup.otto.Bus.dispatch(Bus.java:384)
       at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
       at com.squareup.otto.Bus.post(Bus.java:336)
       at com.ayuget.redface.ui.fragment.TopicListFragment.onContextItemSelected(TopicListFragment.java:480)
       at android.support.v4.app.Fragment.performContextItemSelected(Fragment.java:1909)
       at android.support.v4.app.FragmentManagerImpl.dispatchContextItemSelected(FragmentManager.java:2058)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:359)
       at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:152)
       at com.android.internal.policy.impl.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:4995)
       at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
       at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
       at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
       at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:172)
       at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1019)
       at android.widget.AdapterView.performItemClick(AdapterView.java:334)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1531)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3664)
       at android.widget.AbsListView$3.run(AbsListView.java:5585)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5940)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

Lié au fait qu'on traite un event trop tard. Il faut s'enregistrer / se désenregistrer du bus d'évènement plus tôt dans le cycle de vie de l'Activity / du Fragment

**Comment by Ayuget** [comment]
Corrigé en v1.0.1
