### ISSUE TITLE
Crash userManager

### ISSUE THREAD

**Issue by Ayuget** [Ayuget/Redface#9]
Crash reçu ce matin

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ayuget.redface/com.ayuget.redface.ui.TopicsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ayuget.redface.data.api.model.User.isGuest()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2362)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5466)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:733)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ayuget.redface.data.api.model.User.isGuest()' on a null object reference
       at com.ayuget.redface.account.UserManager.activeUserIsLoggedIn(UserManager.java:54)
       at com.ayuget.redface.ui.BaseDrawerActivity.initiateNavDrawer(BaseDrawerActivity.java:303)
       at com.ayuget.redface.ui.BaseDrawerActivity.setupNavigationDrawer(BaseDrawerActivity.java:121)
       at com.ayuget.redface.ui.BaseDrawerActivity.setContentView(BaseDrawerActivity.java:106)
       at com.ayuget.redface.ui.TopicsActivity.onCreate(TopicsActivity.java:51)
       at android.app.Activity.performCreate(Activity.java:5933)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1116)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2315)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1329)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5466)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:733)
```

**Comment by Ayuget** [comment]
Corrigé en v1.0.1
